// <auto-generated />
using CSIT.Flames.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSIT.Flames.Api.Migrations
{
    [DbContext(typeof(FlamesContext))]
    [Migration("20221030060944_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSIT.Flames.Api.Models.DataDetails", b =>
                {
                    b.Property<int>("Si")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SI")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bname")
                        .HasColumnName("BName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gname")
                        .HasColumnName("GName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Si");

                    b.ToTable("Data_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
